name: Waka Readme

on:
  schedule:
    # æ¯å¤© UTC 16:00ï¼Œä¹Ÿå°±æ˜¯æ¯å¤© é¦™æ¸¯æ—¶é—´ 00:00
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN:      ${{ secrets.GH_TOKEN }}
          repository:    ${{ github.repository }}
          # ä¸‹é¢è¿™äº›æ˜¯å¯é€‰æ˜¾ç¤ºé¡¹ï¼ŒæŒ‰éœ€å¼€å¯
          show_loc_chart:      true
          show_projects:       true
          show_editors:        false
          show_timezone:       true
          show_commit:         true
          show_language:       true
          show_lines_of_code:  true
          show_language_per_repo: false
          show_days_of_week:   true
          show_profile_views:  false
          show_short_info:     true
          show_updated_date:   true
          show_total_code_time: true
          section_name:        "ğŸ“Š My Coding Stats"
